<?php

namespace App\Controller;

use App\Entity\Genre;
use App\Entity\Media;
use App\Form\MediaType;
use App\Repository\GenreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

class MediaController extends Controller
{
    ######### MEDIAS ############
    /**
     * @Route("/media/list", name="media_list")
     */
    public function listMedia(EntityManagerInterface $em)
    {
        $repo = $em->getRepository(Media::class);

        $listeMedias = $repo->findAll();

        return $this->render("media/liste.html.twig",['listeMedias' => $listeMedias]);
    }

    /**
     * @Route("/account/media/create", name="media_create")
     */
    public function createMedia(EntityManagerInterface $em,Request $request)
    {


        $media = new Media();
        $formMedia = $this->createForm(MediaType::class,$media);
        $media->setUtilisateur($this->getUser());
        $media->setDateCreated( new \DateTime());
        $media->setExtension("");
        $formMedia->handleRequest($request);
        if ($formMedia->isSubmitted() && $formMedia->isValid()) {

            $file = $request->files->get('uploadedFile');
            if ($file != null) {
                $fileExtension = $file->getClientOriginalExtension();

                $media->setExtension($fileExtension);

                $picture = array_values($request->files->get('media'))[0];

                $pictureName = $this->generateUniquePictureName();
                $media->setPicture($pictureName);

                $em->persist($media);
                $em->flush();

                // Move the file to the directory where medias are stored
                try {
                    $file->move('files/medias', $media->getId() . '.' . $fileExtension);

                } catch (FileException $e) {
                    $this->addFlash('danger', phpinfo());
                    die();
                }

                // Move the file to the directory where pictures are stored
                try {

                    $picture->move('files/pictures', $pictureName . '.jpg');
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $em->flush();
                $this->addFlash('success', "The media has been created !");

                return $this->redirectToRoute('media_list');
            }
            else
            {
                $this->addFlash('danger', "tu m'prend pour un con ?");
                $this->redirectToRoute('media_create');
            }
        }

        return $this->render(
            'media/form.html.twig',
            array('form' => $formMedia->createView())
        );
    }

    /**
     * @Route("/media/detail/{id}", name="media_detail")
     */
    public function detailMedia(EntityManagerInterface $em, $id = 0)
    {
        $repo = $em->getRepository(Media::class);

        $media = $repo->find($id);

        $genres = $media->getGenre();
        $genre = $genres[0];

        return $this->render('media/detail.html.twig',
            [
                'media'=>$media,
                'typeMedia' => $genre->gettypeMedia()->getName()
            ]);
    }

    /**
     * @Route("/media/delete/{id}", name="media_delete")
     */
    public function deleteMedia(EntityManagerInterface $em, AuthorizationCheckerInterface $authChecker, $id=0)
    {
        $repo = $em->getRepository(Media::class);

        $media = $repo->findById($id);

        $em->remove($media);
        $em->flush();

        $this->addFlash('success', "Media successfully deleted");

        // Redirect to user details
        if ($authChecker->isGranted('ROLE_ADMIN') === true) {

            //TODO get user id to redirect
            return $this->redirectToRoute('user_detail', ['id' => $idUser], 301);
        }

        return $this->redirectToRoute('account');

    }

    /**
     * @return string
     */
    private function generateUniquePictureName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}
